### ISSUE TITLE
Cannot generate docset

### ISSUE THREAD

**Issue by kittinunf** [sirlantis/kotlin-docset#1]
Hey thanks for really useful docset for Kotlin lang. :+1: 

I, however, encountered a problem when trying to generate docset.

when I run `./fetch && ./generate`, it says

> ./fetch: line 20: wget: command not found

Did I do anything wrong?

**Comment by finian** [comment]
@kittinunf You need to install `wget`
If you are using OS X, try this:

```
brew install wget
```

**Comment by kittinunf** [comment]
OK. It works. Perhaps, it is better to document in README.md that you need both `wget` and `ImageMagick` in order to successfully generate docset.

BTW, thanks.

**Comment by mrcljx** [comment]
Wow... I seem to not have noticed that issue... sorry.

Added all the dependencies to the README.
